"""Domain enumerations for the Instagram Browser Automation System."""

from enum import Enum


class TaskType(str, Enum):
    MESSAGE = "MESSAGE"
    FOLLOW_UP_1 = "FOLLOW_UP_1"
    FOLLOW_UP_2 = "FOLLOW_UP_2"


class TaskState(str, Enum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    QUEUED = "QUEUED"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    RETRY_WAIT = "RETRY_WAIT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"
    RECONCILING = "RECONCILING"
    INTERRUPTED = "INTERRUPTED"
    FAILED = "FAILED"


class MessageState(str, Enum):
    PENDING = "PENDING"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    SENDING = "SENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    RECONCILIATION = "RECONCILIATION"


class FollowupStatus(str, Enum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    DUE = "DUE"
    SENT = "SENT"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class RepliedStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    YES = "YES"
    NO = "NO"


class RepliedSource(str, Enum):
    MANUAL = "MANUAL"


class SourceType(str, Enum):
    LOCAL_XLSX = "LOCAL_XLSX"
    BROWSER_SPREADSHEET = "BROWSER_SPREADSHEET"


class SourceAccessStatus(str, Enum):
    ACCESSIBLE = "ACCESSIBLE"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    UNSUPPORTED_STRUCTURE = "UNSUPPORTED_STRUCTURE"


class SyncStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CONFLICT = "CONFLICT"


class VerificationDecision(str, Enum):
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MEDIUM_CONFIDENCE = "MEDIUM_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MISMATCH = "MISMATCH"
    NOT_FOUND = "NOT_FOUND"


class WorkerMode(str, Enum):
    SINGLE_BROWSER = "SINGLE_BROWSER"
    MULTI_BROWSER = "MULTI_BROWSER"


class WorkerStatus(str, Enum):
    IDLE = "IDLE"
    BUSY = "BUSY"
    STOPPED = "STOPPED"
    CRASHED = "CRASHED"
    UNAVAILABLE = "UNAVAILABLE"


class EventLevel(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class EventCode(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_STATE_CHANGED = "TASK_STATE_CHANGED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RETRY_SCHEDULED = "TASK_RETRY_SCHEDULED"
    TASK_INTERRUPTED = "TASK_INTERRUPTED"
    TASK_RECONCILED = "TASK_RECONCILED"
    SOURCE_IMPORTED = "SOURCE_IMPORTED"
    SOURCE_SYNCED = "SOURCE_SYNCED"
    SOURCE_CONFLICT_DETECTED = "SOURCE_CONFLICT_DETECTED"
    CONTACT_CREATED = "CONTACT_CREATED"
    CONTACT_UPDATED = "CONTACT_UPDATED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    FOLLOWUP_CANCELLED = "FOLLOWUP_CANCELLED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    NETWORK_RESTORED = "NETWORK_RESTORED"
    MESSAGE_ATTEMPTED = "MESSAGE_ATTEMPTED"
    MESSAGE_CONFIRMED = "MESSAGE_CONFIRMED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_STOPPED = "WORKER_STOPPED"


class ErrorCode(str, Enum):
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    TIMEOUT = "TIMEOUT"
    BROWSER_CRASH = "BROWSER_CRASH"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"
    DM_NOT_AVAILABLE = "DM_NOT_AVAILABLE"
    MESSAGE_SEND_FAILED = "MESSAGE_SEND_FAILED"
    OCR_LOW_CONFIDENCE = "OCR_LOW_CONFIDENCE"
    UI_CHANGED = "UI_CHANGED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SYNC_CONFLICT = "SYNC_CONFLICT"
    UNKNOWN_RESULT = "UNKNOWN_RESULT"
    INVALID_DATA = "INVALID_DATA"
    DUPLICATE_TASK = "DUPLICATE_TASK"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
