"""Domain enumerations for the Instagram Browser Automation System."""

from enum import Enum


class TaskType(str, Enum):
    MESSAGE = "MESSAGE"
    FOLLOW_UP_1 = "FOLLOW_UP_1"
    FOLLOW_UP_2 = "FOLLOW_UP_2"


class TaskState(str, Enum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    QUEUED = "QUEUED"
    READY = "READY"
    RUNNING = "RUNNING"
    SENDING = "SENDING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    RETRY_WAIT = "RETRY_WAIT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"
    RECONCILING = "RECONCILING"
    INTERRUPTED = "INTERRUPTED"
    FAILED = "FAILED"


class MessageState(str, Enum):
    PENDING = "PENDING"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    SENDING = "SENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    RECONCILIATION = "RECONCILIATION"


class FollowupStatus(str, Enum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    DUE = "DUE"
    SENT = "SENT"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class RepliedStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    YES = "YES"
    NO = "NO"


class RepliedSource(str, Enum):
    MANUAL = "MANUAL"


class SourceType(str, Enum):
    LOCAL_XLSX = "LOCAL_XLSX"
    BROWSER_SPREADSHEET = "BROWSER_SPREADSHEET"


class SourceAccessStatus(str, Enum):
    ACCESSIBLE = "ACCESSIBLE"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    UNSUPPORTED_STRUCTURE = "UNSUPPORTED_STRUCTURE"


class SyncStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CONFLICT = "CONFLICT"


class VerificationDecision(str, Enum):
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    MEDIUM_CONFIDENCE = "MEDIUM_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MISMATCH = "MISMATCH"
    NOT_FOUND = "NOT_FOUND"


class WorkerMode(str, Enum):
    SINGLE_BROWSER = "SINGLE_BROWSER"
    MULTI_BROWSER = "MULTI_BROWSER"


class WorkerStatus(str, Enum):
    IDLE = "IDLE"
    BUSY = "BUSY"
    STOPPED = "STOPPED"
    CRASHED = "CRASHED"
    UNAVAILABLE = "UNAVAILABLE"


class EventLevel(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class EventCode(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_STATE_CHANGED = "TASK_STATE_CHANGED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RETRY_SCHEDULED = "TASK_RETRY_SCHEDULED"
    TASK_INTERRUPTED = "TASK_INTERRUPTED"
    TASK_RECONCILED = "TASK_RECONCILED"
    SOURCE_IMPORTED = "SOURCE_IMPORTED"
    SOURCE_SYNCED = "SOURCE_SYNCED"
    SOURCE_CONFLICT_DETECTED = "SOURCE_CONFLICT_DETECTED"
    CONTACT_CREATED = "CONTACT_CREATED"
    CONTACT_UPDATED = "CONTACT_UPDATED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    FOLLOWUP_CANCELLED = "FOLLOWUP_CANCELLED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    NETWORK_RESTORED = "NETWORK_RESTORED"
    MESSAGE_ATTEMPTED = "MESSAGE_ATTEMPTED"
    MESSAGE_CONFIRMED = "MESSAGE_CONFIRMED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_STOPPED = "WORKER_STOPPED"
    WORKER_CRASHED = "WORKER_CRASHED"
    BROWSER_STARTED = "BROWSER_STARTED"
    BROWSER_STOPPED = "BROWSER_STOPPED"
    BROWSER_CRASHED = "BROWSER_CRASHED"
    BROWSER_SESSION_CREATED = "BROWSER_SESSION_CREATED"
    BROWSER_SESSION_CLOSED = "BROWSER_SESSION_CLOSED"
    SOURCE_OPENED = "SOURCE_OPENED"
    SOURCE_ACCESS_VALIDATED = "SOURCE_ACCESS_VALIDATED"
    SOURCE_ACCESS_DENIED = "SOURCE_ACCESS_DENIED"
    SOURCE_SYNC_STARTED = "SOURCE_SYNC_STARTED"
    SOURCE_SYNC_COMPLETED = "SOURCE_SYNC_COMPLETED"
    SOURCE_SYNC_FAILED = "SOURCE_SYNC_FAILED"
    TASK_CLAIMED = "TASK_CLAIMED"
    TASK_EXECUTION_STARTED = "TASK_EXECUTION_STARTED"
    TASK_EXECUTION_COMPLETED = "TASK_EXECUTION_COMPLETED"
    TASK_EXECUTION_FAILED = "TASK_EXECUTION_FAILED"
    PROFILE_OPENED = "PROFILE_OPENED"
    PROFILE_VERIFIED = "PROFILE_VERIFIED"
    MESSAGE_COMPOSED = "MESSAGE_COMPOSED"
    MESSAGE_SEND_STARTED = "MESSAGE_SEND_STARTED"
    MESSAGE_SEND_ATTEMPTED = "MESSAGE_SEND_ATTEMPTED"
    MESSAGE_SEND_AMBIGUOUS = "MESSAGE_SEND_AMBIGUOUS"
    MESSAGE_VERIFICATION_STARTED = "MESSAGE_VERIFICATION_STARTED"
    MESSAGE_VERIFIED = "MESSAGE_VERIFIED"
    MESSAGE_FAILED = "MESSAGE_FAILED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_RESOLVED = "RECONCILIATION_RESOLVED"
    WORKER_STALE = "WORKER_STALE"
    BROWSER_RECOVERED = "BROWSER_RECOVERED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    TASK_RECOVERED = "TASK_RECOVERED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    LEASE_ACQUIRED = "LEASE_ACQUIRED"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    LEASE_RELEASED = "LEASE_RELEASED"


class ErrorCode(str, Enum):
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    TIMEOUT = "TIMEOUT"
    BROWSER_CRASH = "BROWSER_CRASH"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"
    DM_NOT_AVAILABLE = "DM_NOT_AVAILABLE"
    MESSAGE_SEND_FAILED = "MESSAGE_SEND_FAILED"
    OCR_LOW_CONFIDENCE = "OCR_LOW_CONFIDENCE"
    UI_CHANGED = "UI_CHANGED"
    ACCESS_PROHIBITED = "ACCESS_PROHIBITED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SYNC_CONFLICT = "SYNC_CONFLICT"
    UNKNOWN_RESULT = "UNKNOWN_RESULT"
    INVALID_DATA = "INVALID_DATA"
    DUPLICATE_TASK = "DUPLICATE_TASK"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    ACTION_BLOCKED = "ACTION_BLOCKED"
    CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    LEASE_EXPIRED = "LEASE_EXPIRED"


class ErrorSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InstagramProfileState(str, Enum):
    AVAILABLE = "AVAILABLE"
    NOT_FOUND = "NOT_FOUND"
    PRIVATE = "PRIVATE"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    ACCESS_BLOCKED = "ACCESS_BLOCKED"
    UNKNOWN = "UNKNOWN"


class ReconciliationState(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"


class ReconciliationResolution(str, Enum):
    CONFIRMED_SENT = "CONFIRMED_SENT"
    CONFIRMED_NOT_SENT = "CONFIRMED_NOT_SENT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    RETRY_ALLOWED = "RETRY_ALLOWED"


class SessionAuthState(str, Enum):
    AUTHENTICATED = "AUTHENTICATED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CHECKPOINT = "CHECKPOINT"
    CHALLENGE = "CHALLENGE"
    UNKNOWN = "UNKNOWN"


class RetryClass(str, Enum):
    NETWORK = "NETWORK"
    BROWSER = "BROWSER"
    NAVIGATION = "NAVIGATION"
    RATE_LIMIT = "RATE_LIMIT"
    TEMPORARY_INSTAGRAM = "TEMPORARY_INSTAGRAM"
    MESSAGE_SEND = "MESSAGE_SEND"
    VERIFICATION = "VERIFICATION"
    AUTHENTICATION = "AUTHENTICATION"
    ACCESS_BLOCKED = "ACCESS_BLOCKED"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"
    UNKNOWN = "UNKNOWN"


class ErrorResolution(str, Enum):
    RETRYABLE = "RETRYABLE"
    NON_RETRYABLE = "NON_RETRYABLE"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class DiagnosticType(str, Enum):
    SCREENSHOT = "SCREENSHOT"
    HTML = "HTML"
    PAGE_STATE = "PAGE_STATE"
    ERROR_METADATA = "ERROR_METADATA"
    BROWSER_LOG = "BROWSER_LOG"

